"type" = "yellow"
"constant" = "fg"
"constant.builtin" = { fg = "purple", modifiers = ["italic"] }
"constant.builtin.boolean" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "green"
"string" = "aqua"
"string.regexp" = "green"
"string.special" = "yellow"
"comment" = { fg = "grey1", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = { fg = "purple", modifiers = ["italic"] }
"variable.parameter" = "fg"
"variable.other.member" = "blue"
"label" = "orange"
"punctuation" = "grey2"
"punctuation.delimiter" = "grey1"
"punctuation.bracket" = "fg"
"punctuation.special" = "blue"
"keyword" = "red"
"keyword.operator" = "orange"
"keyword.directive" = "purple"
"keyword.storage" = "red"
"operator" = "orange"
"function" = "green"
"function.macro" = "green"
"tag" = "orange"
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"attribute" = { fg = "purple", modifiers = ["italic"] }
"constructor" = "green"
"module" = "yellow"
"special" = "blue"
"ui.virtual.jump-label" = { fg = "#00dfff", modifiers = ["bold"] }
"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"
"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"
"ui.background" = {}
"ui.background.separator" = "grey0"
"ui.cursor" = { fg = "bg1", bg = "grey2" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey1" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.cursor.match" = { fg = "orange", bg = "bg_yellow" }
"ui.cursor.primary" = { fg = "bg0", bg = "fg" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg2" }
"ui.selection" = { bg = "bg3" }
"ui.linenr" = "grey0"
"ui.linenr.selected" = "grey2"
"ui.statusline" = { fg = "grey2", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "statusline1", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "statusline2", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.bufferline" = { fg = "grey2", bg = "bg3" }
"ui.bufferline.active" = { fg = "bg0", bg = "statusline1", modifiers = ["bold"] }
"ui.popup" = { fg = "grey2", bg = "bg2" }
"ui.picker.header" = { modifiers = ["bold", "underlined"] }
"ui.window" = { fg = "bg4", bg = "bg_dim" }
"ui.help" = { fg = "fg", bg = "bg2" }
"ui.text" = "fg"
"ui.text.directory" = { fg = "green" }
"ui.text.focus" = "fg"
"ui.menu" = { fg = "fg", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.ruler" = { bg = "bg3" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }
"hint" = "green"
"info" = "blue"
"warning" = "yellow"
"error" = "red"
"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
bg_dim = "#faf4ed"
bg0 = "#faf4ed"
bg1 = "#f2e9e1"
bg2 = "#f2e9e1"
bg3 = "#9893a5"
bg4 = "#9893a5"
bg5 = "#9893a5"
bg_visual = "#dfdad9"
bg_red = "#b4637a"
bg_green = "#286983"
bg_blue = "#56949f"
bg_yellow = "#ea9d34"
fg = "#575279"
red = "#b4637a"
orange = "#b4637a"
yellow = "#ea9d34"
green = "#286983"
aqua = "#d7827e"
blue = "#56949f"
purple = "#907aa9"
grey0 = "#9893a5"
grey1 = "#9893a5"
grey2 = "#575279"
statusline1 = "#286983"
statusline2 = "#575279"
statusline3 = "#b4637a"

